#Theory Questions

**1.What are data structures, and why are they important?**


->Data structure is a way of organising and storing of data so that it can be access and manipulated as per requirement effectively.

->list,set,tuple,dict,array are some examples of data structure.

-> Data structure are important because it helps in optimal performace.during code execution data if arranged in a sorted and organised manner , execution is faster.

**2.Explain the difference between mutable and immutable data types with examples.**

->Mutable data types:They can be modified or change as per user requirement once they are defined.

example:- list, l=[1,2,3,4] -here list 'l' is created . now if we want to add more or remove elements in the list we can directly add/remove it using l.append(),l.insert(),l.pop(), l.remove() functions.

l.append(5)
l=[1,2,3,4,5]

->Immutable data types- They cannot be modified or change once they are defined /created.

example:-tupple, t=(1,2,3,4) -here tupple 't' is created. now i cannot modify this tupple after it created.

**3.What are the main differences between lists and tuples in Python?**
->list
1.   list is an ordered and mutable collections of elements
2.   List item which can hold various data tpyes in it.
3.   We can add,remove elements from the list once the list is created, useful for storing data that might change.


example:
 l=[1,2,'apple',5] //list is created here 'l'.
l.append('mango')
l=[1,2,'apple',5,'mango']

->Tupple


1.   Tupple are ordered and immutable collections of elements.
2.   we cannot add,remove elements from the tupple once created.
3.   they are useful for representing fixed datasets.

example:
t=(1,2,3) //tupple is created now we cannot modify this tupple.

**4.Describe how dictionaries store data.**

-> 1.   They are unordered collection of element stored in unspecific order.
2.   they are stored in a "key: value"  pair of manner where key act as unique identifier and has a associated value.
3.   "key: value" can be of any data type(int,string,list,dictionaries)
4.  example: dict1={'one':1,'two':2}

**5.Why might you use a set instead of a list in Python?**

-> 1.   list can store duplicate elements ,Set store only unique elements.So case where we need only unique elements we can use set.
2.   we can perform various operation on set to find common, unique and not in elements between two or more different set.

3.  operations are union,intersection, and difference.

**6. What is a string in Python, and how is it different from a list?**

-> 1.  Strings can be defined as characters assigned in a unchangable order.
2.  They are immutable sequence of characters.
3.  to define a string "" are used.

example: s="Apple"

->1.    A list is a mutable sequence of elements.
2.   can be of any data type.
3.  list is mutable,to define a list [] are used.

example:l[1,2,3,4]

In [ ]:
**7.How do tuples ensure data integrity in Python?**

->1. Tupple are immutable. once defined they cannot be changed, henced maintaing the integrity of data.
2. suppose a set of dataset which once defined we do not want to it change such as a dataset of emplyee IDs .

**8.What is a hash table, and how does it relate to dictionaries in Python?**

->1. hash table is a data structure that stores "key:value" pairs.
2.  Dictionaries in python is an implementation of this hash table.
3. when we define a key:value pair in dictionaries, the key is hashed so as we can find the value associated to the key efficiently.

**9.Can lists contain different data types in Python?**

->YES.

**10. Explain why strings are immutable in Python**

->1. Strings can be used in many important cases where we do not want our datasets to be changed. hence we can safely share and reuse the data once created.
2. to  ensures data integrity and memory optimization.

**11.What advantages do dictionaries offer over lists for certain tasks?**

->1. dictionaries store data in a key:value pair. so when we want to fnd a particular element in dictionaries we can directly call the key and get the associated value .which is comparitively easy.
2.  list store data at indexes so to find the element indexes have to be used.
3. when we want to find any specific data , dictionaries are faster than list.

**12. Describe a scenario where using a tuple would be preferable over a list**

->lets suppose i want to create tupple for storing my Employee ID

empID=(111,222,333,444)

now that my IDs are created i can assign them to the employees.

**13. How do sets handle duplicate values in Python**

->Set only store unique element ,so even if we put duplicate values in the set it would be stored only once.

example:

a={1,1,2,2,3,3,4,4,5,6,7,8}

here, the set 'a' will not stor duplicate values of 1,2,3,4.
so the set a will be.

a={1,2,3,4,5,6,7,8}

**14. How does the “in” keyword work differently for lists and dictionaries**

->3 in [1, 2, 3]  // True , checks if 3 is in the list. it will chek all elements index wise.

'one' in {'key': 1}  // True , checks if 'one' is a key in the dictionary

'1' in {'key': 1}  //False, as in dictionaries it only checks key and not value

**15. Can you modify the elements of a tuple? Explain why or why not**

->NO, tupple are immutable type od data structure.Once defined we can't change or modify the data inside tupple.

**16. What is a nested dictionary, and give an example of its use case ?**

->A nested dictionary is a dictionary inside another dictionary.we can use it to store complex data.
for example details of students.

students =
{
  "raj": {"age": 18, "grade": "A"},

  "taj": {"age": 18, "grade": "A+"}
}

**17. Describe the time complexity of accessing elements in a dictionary**

->findind a value in a dictionary using a key is very fast—usually done in constant time, which is written as O(1). That means it doesn’t get slower as the dictionary gets bigger.

18.  In what situations are lists preferred over dictionaries?

->list can be preferred when we want order of the elements, elements in the list are simple such as numbers or strings .where key value pair are not required.

**19.Why are dictionaries considered unordered, and how does that affect data retrieval?**

->because we access data based on keys and not order in dictionaries. to get the value from the dictionaries we can put the key and get the data which makes it faster.

**20. Explain the difference between a list and a dictionary in terms of data retrieval.**

->In  list, we get items using index numbers, like my_list[0].

In  dictionary, we use keys, like my_dict["name"].

Dictionaries are better when we want to find things by a label or name instead of by position.

#Practical Questions

In [ ]:
#1.Write a code to create a string with your name and print it.
name="Devang"
print(name)

Enter your Name: Devang
Devang

In [ ]:
# 2.Write a code to find the length of the string "Hello World".
print(len("Hello World"))

11

In [ ]:
# 3.Write a code to slice the first 3 characters from the string "Python Programming".
var="Python Programming"
print(var[:3])

Pyt

In [ ]:
#4.Write a code to convert the string "hello" to uppercase.
var="hello"
print(var.upper())

HELLO

In [ ]:
# 5.Write a code to replace the word "apple" with "orange" in the string "I like apple"
var="I like apple"
print(var.replace("apple","orange"))

I like orange

In [ ]:
# 6. Write a code to create a list with numbers 1 to 5 and print it.
var=[1,2,3,4,5]
print(var)

[1, 2, 3, 4, 5]

In [ ]:
# 7.Write a code to append the number 10 to the list [1, 2, 3, 4].
var=[1,2,3,4]
var.append(10)
print(var)

[1, 2, 3, 4, 10]

In [ ]:
# 8.Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].
var=[1, 2, 3, 4, 5]
var.remove(3)
print(var)

[1, 2, 4, 5]

In [ ]:
# 9.Write a code to access the second element in the list ['a', 'b', 'c', 'd'].
var=['a', 'b', 'c', 'd']
print(var[1])

b

In [ ]:
# 10.Write a code to reverse the list [10, 20, 30, 40, 50].
var=[10, 20, 30, 40, 50]
print(var[5::-1])

[50, 40, 30, 20, 10]

In [ ]:
# 11.Write a code to create a tuple with the elements 100, 200, 300 and print it.
var=(100,200,300)
print(var)

(100, 200, 300)

In [ ]:
#12.Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').
var=('red', 'green', 'blue', 'yellow')
print(var[1:])

('green', 'blue', 'yellow')

In [ ]:
# 13.Write a code to find the minimum number in the tuple (10, 20, 5, 15).
var=(10, 20, 5, 15)
print(min(var))

5

In [ ]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
var=('dog', 'cat', 'rabbit')
print(var.index('cat'))

1

In [ ]:
# 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it
var=("Apple","Orange","kiwi")
print("kiwi" in var)

True

In [ ]:
# 16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.
var={"a","b","c"}
print(var)

{'a', 'b', 'c'}

In [ ]:
# 17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.
var={1, 2, 3, 4, 5}
print(var.clear())

None

In [ ]:
# 18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.
var={1, 2, 3, 4}
var.remove(4)
print(var)

{1, 2, 3}

In [ ]:
# 19.Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.
var1={1,2,3}
var2={3,4,5}

_union= var1 | var2
print(_union)

{1, 2, 3, 4, 5}

In [ ]:
# 20.Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.
var1={1,2,3}
var2={2,3,4}

_intersection= var1 & var2
print(_intersection)

{2, 3}

In [ ]:
# 21.Write a code to create a dictionary with the keys "name", "age", and "city", and print it.
dict1={"name":"Devang","age":23,"city":"Panjim"}
print(dict1)

{'name': 'Devang', 'age': 23, 'city': 'Panjim'}

In [ ]:
#22.Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.
dict1={'name': 'John', 'age': 25}
dict1["country"]= "USA"
print(dict1)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [ ]:
# 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.
dict1= {'name': 'Alice', 'age': 30}
print(dict1["name"])

Alice

In [ ]:
# 24.Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.
dict1={'name': 'Bob', 'age': 22, 'city': 'New York'}
del dict1["age"]
print(dict1)

{'name': 'Bob', 'city': 'New York'}

In [ ]:
# 25.Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.
dict1={'name': 'Alice', 'city': 'Paris'}
if 'city' in dict1:
  print("The key 'city' exists in the dictionary")
else:
    print("The key 'city' does not exists in the dictionary")

The key 'city' exists in the dictionary

In [ ]:
# 26.Write a code to create a list, a tuple, and a dictionary, and print them all.
list1=[1,2,3,4,5]
tuple1=(1,2,3,4,5)
dict1={"age":22,"a":"A"}

print("list:",list1)
print("tuple:",tuple1)
print("dict:",dict1)

list: [1, 2, 3, 4, 5]
tuple: (1, 2, 3, 4, 5)
dict: {'age': 22, 'a': 'A'}

In [ ]:
# 27.Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)
list1=[58,78,1,5,99]
list1.sort()
print(list1)

[1, 5, 58, 78, 99]

In [ ]:
# 28.Write a code to create a list with strings and print the element at the third index.
var=['Apple','banana','kiwi','mango','muskmelon']
print(var[3])

mango

In [ ]:
# 29.Write a code to combine two dictionaries into one and print the result.
dict1={"one":1,"two":2}
dict2={"three":3,"four":4}

dict3=dict1 | dict2
print(dict3)

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

In [ ]:
# 30.Write a code to convert a list of strings into a set.
var=['Apple','banana','kiwi','mango','muskmelon']
print(set(var))

{'banana', 'mango', 'muskmelon', 'Apple', 'kiwi'}